import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { ApiOrder } from "../store/apiSlice";

export function OrdersView({ orders, isLoading }: { orders: ApiOrder[]; isLoading: boolean }) {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("ALL");
  const [expanded, setExpanded] = useState<string | null>(null);
  const visible = useMemo(() => orders.filter((order) => {
    const matchesStatus = status === "ALL" || order.status === status;
    const query = search.trim().toLowerCase();
    return matchesStatus && (!query || `${order.orderNumber ?? ""} ${order.user?.name ?? ""} ${order.user?.email ?? ""}`.toLowerCase().includes(query));
  }), [orders, search, status]);
  return <main className="flex-1 overflow-y-auto p-7"><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-sky-300">Sales</p><h1 className="mt-2 text-3xl font-black text-white">Orders</h1><p className="mt-1 text-sm text-slate-400">Search and review recent orders from this store.</p></header>
    <section className="mb-5 flex flex-wrap items-center gap-3"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order number or cashier" className="w-full rounded-xl border border-slate-800 bg-slate-900 py-2.5 pl-10 pr-4 text-sm text-white outline-none focus:border-sky-500" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-slate-800 bg-slate-900 px-4 py-2.5 text-sm text-slate-200 outline-none"><option value="ALL">All statuses</option>{[...new Set(orders.map((order) => order.status))].map((value) => <option key={value} value={value}>{value}</option>)}</select><span className="text-xs text-slate-500">{visible.length} orders</span></section>
    <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/70"><div className="grid grid-cols-[1.4fr_1fr_1fr_1fr_auto] gap-4 border-b border-slate-800 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-500"><span>Order</span><span>Date</span><span>Cashier</span><span className="text-right">Total</span><span>Status</span></div>{isLoading ? <p className="p-10 text-center text-sm text-slate-400">Loading orders…</p> : visible.length === 0 ? <p className="p-10 text-center text-sm text-slate-400">No orders match these filters.</p> : visible.map((order) => <div key={order.id} className="border-b border-slate-800/70 last:border-0"><button onClick={() => setExpanded(expanded === order.id ? null : order.id)} className="grid w-full grid-cols-[1.4fr_1fr_1fr_1fr_auto] items-center gap-4 px-5 py-4 text-left hover:bg-slate-800/40"><span className="truncate text-sm font-semibold text-white">{order.orderNumber || order.id.slice(0, 8)}</span><span className="text-xs text-slate-400">{new Date(order.createdAt).toLocaleString()}</span><span className="truncate text-xs text-slate-300">{order.user?.name || order.user?.email || "—"}</span><span className="text-right text-sm font-bold text-white">{order.grandTotal.toLocaleString()} MMK</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${order.status === "COMPLETED" ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-300"}`}>{order.status}</span></button>{expanded === order.id && <div className="bg-slate-950/60 px-5 py-4">{order.items?.length ? <div className="space-y-2">{order.items.map((item) => <div key={item.id} className="flex justify-between gap-4 text-xs"><span className="text-slate-300">{item.product?.name || "Product"} × {item.quantity}</span><span className="text-slate-400">{Number(item.subTotal).toLocaleString()} MMK</span></div>)}</div> : <p className="text-xs text-slate-500">No line item detail returned.</p>}<p className="mt-3 border-t border-slate-800 pt-3 text-xs text-slate-500">Payment: {order.paymentMethod || "—"} · {order.paymentStatus || order.status}</p></div>}</div>)}</section>
    <p className="mt-3 text-xs text-slate-500">Showing up to 100 recent server records. Older orders require pagination.</p>
  </main>;
}
